spring.application.name=springboot-langchain4j-dashscope
server.port=8090

# ????? key?????????????
dashscope.api-key=${DASHSCOPE_API_KEY:}
dashscope.model=${DASHSCOPE_MODEL:qwen-turbo}
dashscope.temperature=${DASHSCOPE_TEMPERATURE:0.7}


langchain4j.open-ai.chat-model.api-key=${DASHSCOPE_API_KEY}
langchain4j.open-ai.chat-model.model-name=qwen-plus
langchain4j.open-ai.chat-model.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
